const MERCHANDISE_CONVERSION = 'MERCHANDISE-CONVERSION';
const MERCHANDISE_LIST = 'MERCHANDISE-LIST';
const MERCHANDISE_TOTAL = 'MERCHANDISE-TOTAL';
const MERCHANDISE_FIND = 'MERCHANDISE-FIND';

const ADVERTISEMENT_LIST = 'ADVERTISEMENT-LIST';

const SIGNIN_DATA = 'SIGNIN-DATA';
const SIGNIN_UPDATE = 'SIGNIN-UPDATE';

module.exports = {
  MERCHANDISE_LIST,
  MERCHANDISE_TOTAL,
  MERCHANDISE_FIND,
  MERCHANDISE_CONVERSION,
  ADVERTISEMENT_LIST,
  SIGNIN_DATA,
  SIGNIN_UPDATE,
};